# Generated by Django 4.1.4 on 2023-10-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreadingtime',
            name='session_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='last_read_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
