# Generated by Django 4.1.4 on 2023-10-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bookreadingtime_session_counter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreadingtime',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookreadingtime',
            name='reading_time',
        ),
        migrations.RemoveField(
            model_name='bookreadingtime',
            name='session_counter',
        ),
        migrations.AddField(
            model_name='bookreadingtime',
            name='books',
            field=models.JSONField(default=dict),
        ),
    ]
