# Generated by Django 4.1.4 on 2023-10-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_bookreadingtime_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreadingtime',
            name='total_reading_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bookreadingtime',
            name='total_session_counter',
            field=models.IntegerField(default=0),
        ),
    ]
