# Generated by Django 4.1.4 on 2023-10-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_readingstatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
